### ISSUE TITLE
Where may I update the dismatched ``habitat_sim``?

### ISSUE THREAD

**Issue by Yonggie** [facebookresearch/home-robot#482]
## 🐛 Bug
I'm using ``habitat-lab 0.2.5`` and ``home-robot-sim ==0.1.0``, found version dismatch:
```
NameError: pbr_image_based_lighting is not found on habitat_sim but is found on habitat_lab config.
                    It's also not in the list of keys to ignore: {'gpu_gpu'}
                    Did you make a typo in the config?
                    If not the version of Habitat Sim may not be compatible with Habitat Lab version: {'gpu_device_id': 0, 'gpu_gpu': False, 'allow_sliding': False, 'frustum_culling': True, 'enable_physics': True, 'physics_config_file': './data/default.physics_config.json', 'leave_context_with_background_renderer': False, 'enable_gfx_replay_save': False, 'pbr_image_based_lighting': True}
                    
Exception ignored in: <function Simulator.__del__ at 0x2b8d28d498b0>
Traceback (most recent call last):
  File "/home/planner/anaconda3/envs/habitat_latest/lib/python3.9/site-packages/habitat_sim-0.3.1-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 528, in __del__
    self.close(destroy=True)
  File "/home/planner/anaconda3/envs/habitat_latest/lib/python3.9/site-packages/habitat_sim-0.3.1-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 131, in close
    if not self._initialized:
AttributeError: 'OVMMSim' object has no attribute '_initialized'
```

**Comment by yvsriram** [comment]
It seems like you installed habitat_sim 0.3.1. This is not currently supported. Please install `habitat_sim==0.2.5` when working with `habitat-lab 0.2.5`

**Comment by Yonggie** [comment]
I see, the version of ``habitat-lab`` and ``habitat-sim`` should be exactly the same.

**Comment by Yonggie** [comment]
Use this ``conda install habitat-sim==0.2.5 -c conda-forge -c aihabitat`` to install specified version of habitat-sim! 
- https://github.com/facebookresearch/habitat-sim
